version: '3.8'
services:
  stats-server:
    build: ./
    image: myshop-image
    container_name: myshop
    depends_on:
      - myshop-db
    ports:
      - "8080:8080"
    environment:
      - DB_NAME=myshop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - DB_HOST=myshop-db
      - DB_PORT=5432

  myshop-db:
    image: postgres:15.1-alpine
    container_name: myshop-db
    ports:
      - "5433:5432"
    volumes:
      - /myshop
    environment:
      - POSTGRES_DB=myshop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin