version: '3.8'
services:
  storefront-server:
    build: ./storefront
    image: storefront-image
    container_name: storefront
    depends_on:
      - myshop-db
      - redis
      - keycloak
    ports:
      - "8080:8080"
    environment:
      - DB_NAME=myshop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - DB_HOST=myshop-db
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=admin
      - PAYMENT_URL=http://payment-server:8081

  payment-server:
    build: ./payment
    image: payment-image
    container_name: payment
    depends_on:
      - myshop-db
      - keycloak
    ports:
      - "8081:8081"
    environment:
      - DB_NAME=myshop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - DB_HOST=myshop-db
      - DB_PORT=5432


  myshop-db:
    image: postgres:15.1-alpine
    container_name: myshop-db
    ports:
      - "5433:5432"
    volumes:
      - /myshop
    environment:
      - POSTGRES_DB=myshop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - /redis_data
    environment:
      - REDIS_PASSWORD=admin
    command: ["redis-server", "--requirepass", "admin"]

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: keycloak
    ports:
      - "8082:8082"
    environment:
      - KC_HTTP_PORT=8082
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    command: [ "start-dev" ] # Запуск в режиме разработки