server:
  port: 8081

spring:
  application:
    name: payment
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:myshop}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD}
    pool:
      enabled: true
      initial-size: 10
      max-size: 50
      max-idle-time: 30s
      max-life-time: 10m
      validation-query: SELECT 1

  liquibase:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:myshop}
    user: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD}
    change-log: classpath:db/changelog/changelog-master.xml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8082}/realms/master