openapi: 3.0.4
info:
  title: Payment Service API
  description: API сервиса платежей
  version: 1.0.0
paths:
  /account/balance/{accountId}:
    get:
      tags:
        - account
      summary: Получить баланс на счете
      parameters:
        - $ref: '#/components/parameters/AccountId'
      responses:
        '200':
          description: Успешный ответ
          headers:
            X-ver:
              $ref: '#/components/headers/X-Ver'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceResponseDto'
        '500':
          description: Внутреняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
  /account/processPayment:
    patch:
      tags:
        - account
      summary: Оформление заказа
      parameters:
        - name: X-Ver
          in: header
          description: версия баланса
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProcessPaymentDto'
      responses:
        '200':
          description: Платеж успешно проведен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceResponseDto'
        '409':
          description: Состояние счета было изменено. Обновите страницу и попробуйте снова
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '500':
          description: Внутреняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

tags:
  - name: account
    description: Взаимодействие с аккаунтом пользователя

components:
  headers:
    X-Ver:
      description: версия баланса
      required: true
      schema:
        type: integer

  schemas:
    BalanceResponseDto:
      description: Текущий баланс
      type: object
      properties:
        balance:
          type: number
          example: 10.5
    ProcessPaymentDto:
      type: object
      required:
        - orderSum
        - accountId
      properties:
        orderSum:
          type: number
          example: 10.5
        accountId:
          type: integer
          format: int64
          example: 3252352
    ApiError:
      description: описание ошибки
      type: object
      properties:
        code:
          type: string
          example: 404
        message:
          type: string
          example: аккаунт не найден

  parameters:
    AccountId:
      name: accountId
      in: path
      description: идентификатор пользователя
      required: true
      schema:
        type: integer
        format: int64