spring:
  r2dbc:
    url: r2dbc:h2:mem:///myshop
    username: sa
    password:
    pool:
      enabled: true
      initial-size: 10
      max-size: 50
      max-idle-time: 30s
      max-life-time: 10m
      validation-query: SELECT 1

  liquibase:
    url: jdbc:h2:mem:myshop;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    user: sa
    password:
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: false


  h2:
    console:
      enabled: true #http://localhost:8080/h2-console