spring:
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:myshop}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD}
    pool:
      enabled: true
      initial-size: 10
      max-size: 50
      max-idle-time: 30s
      max-life-time: 10m
      validation-query: SELECT 1

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
      password: ${REDIS_PASSWORD:admin}
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  session:
    #store-type: redis
    timeout: 1800s

  cache:
    type: redis
    redis:
      time-to-live: PT1M

  liquibase:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:myshop}
    user: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD}
    change-log: classpath:db/changelog/changelog-master.xml

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_URL:http://localhost:8082}/realms/master
        registration:
          storefront:
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: storefront
            client-secret: 6kUHHf0Y1vR8bBGcAJhVeOegWhYuQtwY
            scope: profile
            clientAuthenticationMethod: client_secret_post

admin:
  login: ${ADMIN_LOGIN:admin}
  password: ${ADMIN_PASSWORD:1234}
  role: ${USER_ROLE:ADMIN}

rest:
  account-service:
    host:  ${PAYMENT_URL:http://localhost:8081}
    methods:
      patch-processOrder: /account/processPayment
      get-getBalance: /account/balance/{userIp}